# Generated by Django 3.1 on 2020-08-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200807_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Article1',
        ),
    ]
