# Generated by Django 3.1 on 2020-08-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200807_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article1',
            new_name='Article',
        ),
    ]
